baseURL = "https://www.boosterconf.no/2027"
languageCode = "en-us"
title = "Booster Conference 2027 Bergen"
theme = "booster"
publishDir = "public/2027"

[params]
  currentYear = "2027"

[module]
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"