baseURL = "https://www.boosterconf.no/2026"
languageCode = "en-us"
title = "Booster Conference 2026 Bergen"
theme = "booster"
publishDir = "public/2026"

[module]
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"