name: Build program_import

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./program_import
      run: cargo build --locked --release
    - name: Run tests
      working-directory: ./program_import
      run: cargo test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        # Artifact name
        name: program_import
        # A file, directory or wildcard pattern that describes what to upload
        path: ./program_import/target/release/program_import
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
