name: auto-import program

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12,20 * 02 *"
    - cron: "0 12,20 1-11 03 *"
    - cron: "45 06-15 11,12,13 03 *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Cache dependencies"
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
      with:
        workspaces: program_import
        cache-on-failure: true
    - name: Build
      working-directory: ./program_import
      run: cargo run --locked --verbose
    - run: git add content
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - run: git commit -m "Automatic program import"
    - run: git push
